name: Build

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild build
      run: xcodebuild clean build -project MVVM_Exercise/MVVM_Exercise.xcodeproj -scheme MVVM_Exercise -destination "platform=iOS Simulator,name=iPhone 11 pro"
